# Generated by Django 3.2.16 on 2023-01-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='1', upload_to='picture'),
            preserve_default=False,
        ),
    ]
