# Generated by Django 3.2.16 on 2023-02-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='month',
            field=models.TextField(),
        ),
    ]
